Numerical and Categorical Pre-Processing PR
Avdhesh-Varshney/AI-Code pull request #29
Opened 2024-06-10 07:33 UTC by Lycons-rage

Closes: #18 [FEATURE REQUEST] Adding Pre-Processing Techniques for numerical as well as categorical features 

- **Title** : Standardization, Normalization, Ordinal Encoding Complete
- **Name:** Chinmaya Tewari (Lycons-rage) 
- **Idenitfy yourself:** SSOC Contributor

### Describe the add-ons or changes you've made 📃

Added 3 directories, named, Min_Max_Scaler (Normalization), Standard_Scaler (Standardization), Ordinal_Encoding (Categorical Feature Handling), each having testing and images subdirectories along with the python script and testing files and respective readme.md files.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

![Screenshot 2024-06-10 130158](https://github.com/Avdhesh-Varshney/AI-Code/assets/51325697/b34062e1-c6d8-43cf-88d8-1fdf8d23316b)

2024-06-10 14:29 UTC, Avdhesh-Varshney requested changes
@Lycons-rage LGTM. do these necessary changes.

2024-06-10 14:29 UTC, Avdhesh-Varshney commented on Pre-Processing/Algorithms/requirements.txt
remove this file. not required.

2024-06-10 14:29 UTC, Avdhesh-Varshney commented on Python-Scripts/Practice Problems/Python Programs on Math Functions/Python Program to Form an Integer that has the Number of Digits at Ten’s Place and the Least Significant Digit of the Entered Integer at One’s Place.py
don't delete any file. revoke it.

2024-06-10 14:38 UTC, Lycons-rage commented on Python-Scripts/Practice Problems/Python Programs on Math Functions/Python Program to Form an Integer that has the Number of Digits at Ten’s Place and the Least Significant Digit of the Entered Integer at One’s Place.py
> don't delete any file. revoke it.

I would've deleted it by mistake...my bad

2024-06-10 14:39 UTC, Lycons-rage commented on Pre-Processing/Algorithms/Min_Max_Scaler/README.md
> +- Prints an error message if transformation is attempted before fitting the scaler.
Should I elaborate the line in readme.md file?

2024-06-11 04:12 UTC, Avdhesh-Varshney commented on Pre-Processing/Algorithms/Min_Max_Scaler/README.md
> +- Prints an error message if transformation is attempted before fitting the scaler.
no explain it only in chat only last line.

2024-06-11 10:47 UTC, Lycons-rage commented on Pre-Processing/Algorithms/Min_Max_Scaler/README.md
> +- Prints an error message if transformation is attempted before fitting the scaler.
The last line says that if a user tries to call transform function directly, without either calling fit function or fit_transform function first, it will return an exception as fit function calculates the required parameters on the dataset, which, in this case (Min_Max_Scaler) are the minimum and maximum values of each feature. Without them we cannot transform the data.

2024-06-12 06:18 UTC, Avdhesh-Varshney commented
@Lycons-rage you have not committed the required to change so to reflect on the pr

2024-06-12 06:23 UTC, Lycons-rage commented
@Avdhesh-Varshney I'm facing some issues with my laptop, I'll do it by today for sure

2024-06-12 07:17 UTC, Lycons-rage commented
> @Lycons-rage LGTM. do these necessary changes. Also enlist these algorithms in the readme file created by me.

@Avdhesh-Varshney Could you please tell me in which readme file should i enlist the algorithms

2024-06-15 09:41 UTC, closed without merging