Fixed Issue #20 [Feature Request] Add loss functions for classification tasks
Avdhesh-Varshney/AI-Code pull request #30
Opened 2024-06-11 13:23 UTC by arijitde92

Closes: #20

- **Title** : Add loss functions for classification tasks
- **Name:** Arijit De
- **Idenitfy yourself:** SSoC'24 Contributor

### Describe the add-ons or changes you've made 📃

Added implementations of hinge loss, KL Divergence loss and four versions of cross entropy loss from scratch using numpy.
The implementations also contains results with some sample data.
Also updated the README.md file inside ML directory with the links to the directories of the said loss functions.

### Type of change ☑️

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

It has been tested with sample data and the test code is also available in the respective loss function files.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

Cross Entropy loss
![CE_Loss](https://github.com/Avdhesh-Varshney/AI-Code/assets/12524022/1953aa8e-9774-4776-bfcf-027c02d07673)

Hinge Loss
![hinge_loss](https://github.com/Avdhesh-Varshney/AI-Code/assets/12524022/45721031-17b8-4994-a37c-e156c97f4f55)

KL-Divergence Loss
![Screenshot 2024-06-11 185102](https://github.com/Avdhesh-Varshney/AI-Code/assets/12524022/d693fcaf-d62a-41fc-b8e7-171d677eb27f)

### Note to reviewers 📄

2024-06-12 06:31 UTC, Avdhesh-Varshney requested changes
@arijitde92 LGTM.

2024-06-12 06:31 UTC, Avdhesh-Varshney commented on ML/Algorithms/Losses/HingeLoss/hinge_loss.py
> +    y_true = np.where(y_true == 0, -1, 1)
why we have replacing some values from 0 to -1? explain it here.

2024-06-12 08:32 UTC, arijitde92 commented on ML/Algorithms/Losses/HingeLoss/hinge_loss.py
> +    y_true = np.where(y_true == 0, -1, 1)
Hinge loss acts as a maximum margin classifier (like SVM) and according to [Wikipedia](https://en.wikipedia.org/wiki/Hinge_loss) of Hinge Loss, the mathematical definition states that the label values should be 1 and -1.
See below screenshot
![image](https://github.com/Avdhesh-Varshney/AI-Code/assets/12524022/8d6151bb-93e3-44b4-9545-1fd30622e1c4)

2024-06-14 07:11 UTC, Avdhesh-Varshney approved these changes
@arijitde92 PR Approved 🎉

2024-06-14 07:11 UTC, merged