Add files via upload
Avdhesh-Varshney/AI-Code pull request #55
Opened 2024-06-24 06:40 UTC by UTSAVS26

Closes: #22 

- **Title**: Added Various GAN Architectures for Medical Imaging
- **Name:** Utsav Singhal
- **Identify yourself:** SSOC'24 Contributor

### Describe the add-ons or changes you've made 📃

Implemented the following GAN architectures for medical imaging:
- BasicGAN
- ACGAN
- cGAN
- EBGAN
- InfoGAN

### Type of change ☑️

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested? ⚙️

Tested locally to ensure each GAN model functions correctly and generates synthetic medical images as expected. Unit tests for Basic GAN are in place and runnable with `python -m unittest test_BasicGAN.py`.

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Note to reviewers 📄

Please review the added GAN models for correctness and adherence to project standards. Thank you!

2024-06-28 03:54 UTC, Avdhesh-Varshney requested changes
@UTSAVS26 enlist these algorithms in readme file of `GAN`

2024-06-28 03:54 UTC, Avdhesh-Varshney commented on GAN/Algorithms/README.md
not required.

2024-06-28 03:54 UTC, Avdhesh-Varshney commented on GAN/Algorithms/requirements.txt
not required.

2024-06-28 08:29 UTC, UTSAVS26 commented
> @UTSAVS26 enlist these algorithms in readme file of `GAN`

All the algorithms as been listed in the readme file of `GAN` and successfully removed unrequired files as mentioned.

2024-07-05 10:51 UTC, Avdhesh-Varshney approved these changes

2024-07-05 10:51 UTC, merged