Cardiovascular Diseas Prediction Model
Avdhesh-Varshney/AI-Code pull request #64
Opened 2024-07-08 13:31 UTC by siddhant4ds

Closes:  #37

- **Title** : Cardiovascular Disease Prediction Model
- **Name:**  Siddhant Tiwari
- **Idenitfy yourself:**  SSOC-3 (2024) Contributor

### Describe the add-ons or changes you've made 📃

* Linked a notebook which includes:
1. Exploratory Data Analysis of the dataset
2. Data cleaning and preprocessing as required for different ML algorithms
3. Feature engineering based on domain knowledge.
4. Feature selection based on correlation scores.
5. Model implemented: Logistic Regression, Decision Tree, Random Forest, AdaBoost, Hist-Gradient Boosting and Multi-Layer Perceptron neural network.
6. Post-tuning of prediction thresholds for models for more accurate predictions.
7. Result analysis using confusion matrices.

* Added a README which includes the project details and images generated.

### Type of change ☑️

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

### How Has This Been Tested? ⚙️

Model reproducibility: Setting random seed and multiple runs of the models to ensure stable results.
Dependencies: Running the notebook in local environment as well as cloud-hosted notebooks (Kaggle).

### Checklist: ☑️

- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

### Screenshots 📷

![scrshot1](https://github.com/Avdhesh-Varshney/AI-Code/assets/150765441/4afb4ae2-5c2a-41bc-bc9a-e893d3f06e11)
![scrshot2](https://github.com/Avdhesh-Varshney/AI-Code/assets/150765441/a163b23d-b5e9-4dc7-9d0c-d3e787727e6d)
![scrshot3](https://github.com/Avdhesh-Varshney/AI-Code/assets/150765441/a9f46007-b3aa-4991-8ec2-07505c57bd6f)
![scrshot4](https://github.com/Avdhesh-Varshney/AI-Code/assets/150765441/7da4d7ff-ad42-4aca-8a7e-a212c8dd70c9)
![scrshot5](https://github.com/Avdhesh-Varshney/AI-Code/assets/150765441/2855fbda-7bc3-4bf9-9615-5e56bc3493c2)

### Note to reviewers 📄

2024-07-09 04:00 UTC, Avdhesh-Varshney requested changes
@siddhant4ds LGTM.

2024-07-09 04:00 UTC, Avdhesh-Varshney commented on ML/Projects/cardiovascular_disease_prediction/README.md
> +# Project Title
change it by the name of project

2024-07-09 07:57 UTC, siddhant4ds commented on ML/Projects/cardiovascular_disease_prediction/README.md
> +# Project Title
Sorry, missed that between multiple versions of the README. 
Updated the project title. Let me know if any other changes are required. Thanks.

2024-07-10 03:51 UTC, Avdhesh-Varshney approved these changes

2024-07-10 03:52 UTC, merged