Add the email_spam_detection directory in NLP/projects
Avdhesh-Varshney/AI-Code pull request #88
Opened 2024-12-16 11:50 UTC by ikcod

Added the email_spam_detection project in NLP/projects

Closes: #86 

- **Title**  :  Email_Spam_Detection
- **Your Name:**  Insha Khan
- **Idenitfy yourself:** KwoC Contributor

### Describe the add-ons or changes you've made 📃

- I have added the email_spam_detection project in the NLP/projects directory
- This project contatins the jupyter file , dataset used in the project and a read me file that explains the project

### Checklist: ☑️
- [x] My code follows the [Contributing Guidelines](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/README.md) & [Code of Conduct](https://github.com/Avdhesh-Varshney/AI-Code/blob/main/CODE_OF_CONDUCT.md) of this project.
- [x] This PR does not contain plagiarized content.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.

2024-12-17 12:01 UTC, Avdhesh-Varshney requested changes
You can take refrence from here and also attach a video how your project page looks like.

`https://avdhesh-varshney.github.io/AI-Code/NLP/projects/twitter_sentiment_analysis/`

2024-12-17 12:01 UTC, Avdhesh-Varshney commented on docs/NLP/projects/Email_Spam_Detection/email.ipynb
Upload it either on drive or kaggle.
Just attach the link of the notebook.

2024-12-17 12:01 UTC, Avdhesh-Varshney commented on docs/NLP/projects/Email_Spam_Detection/mail_data.csv
Dataset not required.

2024-12-18 18:04 UTC, ikcod commented
Completed the required changes.

2024-12-18 18:26 UTC, Avdhesh-Varshney requested changes
Attach a video

2024-12-18 18:26 UTC, Avdhesh-Varshney commented on docs/NLP/projects/Email_Spam_Detection/README.md
> +[https://www.kaggle.com/datasets/ashfakyeafi/spam-email-classification](link)
link?

2024-12-18 18:26 UTC, Avdhesh-Varshney commented on docs/NLP/projects/Email_Spam_Detection/README.md
> +[https://www.kaggle.com/code/inshak9/email-spam-detection](link)
link

2024-12-18 18:26 UTC, Avdhesh-Varshney commented on docs/NLP/projects/Email_Spam_Detection/README.md
> +***Your Name***
.

2024-12-18 18:49 UTC, ikcod commented
Video of project page after adding the links to dataset and kaggle notebook

https://github.com/user-attachments/assets/7619d706-48a9-4725-9f83-4207cbc51291

2024-12-18 19:00 UTC, Avdhesh-Varshney approved these changes
It looks good. But there are some issues like,
- Committed directly in `main` branch.
- I required a video of the project documentation page not project github page.

You should join the discord server/ github discussion for faster communication.

2024-12-18 19:00 UTC, merged

2024-12-18 19:05 UTC, Avdhesh-Varshney commented
https://avdhesh-varshney.github.io/AI-Code/NLP/projects/Email_Spam_Detection/

Review this project page on your own.